Repository TripleSync/TS, pull requests merged in 2024-11, with the labels that each got.

#21 화상채팅 디자인
  src/components/ClassRoom/VideoChat.tsx
  src/components/ClassRoom/VideoChat/Controls.tsx
  src/components/ClassRoom/VideoChat/Video.tsx
  src/components/ClassRoom/VideoChat/VolumeControls.tsx
  src/page/ClassRoom.tsx
Labels: design

#23 그림판 디자인 수정
  src/components/ClassRoom/Chat.tsx
  src/components/ClassRoom/Drawing.tsx
  src/components/ClassRoom/Drawing/ColorBtn.tsx
  src/components/ClassRoom/Drawing/Tool.tsx
  src/components/ClassRoom/Drawing/Tools.tsx
  src/components/ClassRoom/Drawing/ToolsContainer.tsx
Labels: feat, design

#24 그림판 내용 저장
  server/server.js
  src/components/ClassRoom/Drawing.tsx
Labels: feat, refactor

#25 feat: 프로필 사진 url로 구현
  src/components/Login/LoginInput.tsx
  src/components/layout/Modal.tsx
  src/components/layout/Nav.tsx
  src/hooks/useLogin.ts
  src/page/SignUp.tsx
  src/router/ProtectedRoute.tsx
  src/router/Router.tsx
Labels: feat, design
