Repository TripleSync/TS, pull requests merged in 2024-10, with the labels that each got.

#2 Feature/chat
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/server.js
  src/assets/user1.svg
  src/components/ClassRoom/Chat.tsx
  src/main.tsx
  src/page/ClassRoom.tsx
  src/store/actions/useChatStore.ts
  src/store/types/chatStoreType.d.ts
  src/types/chat.d.ts
  src/types/user.d.ts
  src/utils/date.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: feat

#4 refactor: 채팅 컴포넌트 모듈화 및 최적화
  src/components/ClassRoom/Chat.tsx
  src/components/ClassRoom/ChatInput.tsx
  src/components/ClassRoom/ChatMessage.tsx
  src/page/ClassRoom.tsx
Labels: refactor

#13 그림판 기능
  package-lock.json
  package.json
  src/assets/problem-ex.jpg
  src/components/ClassRoom/Drawing.tsx
  src/components/ClassRoom/Drawing/ColorBtn.tsx
  src/components/ClassRoom/Drawing/Tool.tsx
  src/page/ClassRoom.tsx
  src/store/actions/useDrawngStore.ts
  src/types/drawing.d.ts
Labels: feat, design

#14 필기 소켓전달 기능 추가
  server/server.js
  src/components/ClassRoom/Drawing.tsx
Labels: feat

#10 화상채팅 기능 구현
  package-lock.json
  package.json
  server/server.js
  src/components/VideoChat/Controls.tsx
  src/components/VideoChat/VideoChat.tsx
  src/components/VideoChat/VolumeControls.tsx
  src/router/Router.tsx
Labels: feat

#12 design: 로그인, 회원가입 페이지 마크업
  src/components/Login/LoginButton.tsx
  src/components/Login/LoginInput.tsx
  src/components/Login/LogoArea.tsx
  src/hooks/useInput.tsx
  src/page/Login.tsx
  src/page/SignUp.tsx
  src/router/Router.tsx
Labels: design
