Repository TripleSync/TS, pull requests merged in 2024-12, with the labels that each got.

#27 feat: 회원가입 role 추가, 로그인페이지 protect 설정
  src/components/layout/Modal.tsx
  src/hooks/useLogin.ts
  src/page/SignUp.tsx
  src/router/ProtectedRoute.tsx
  src/router/Router.tsx
  src/store/actions/useUserStore.ts
  src/types/user.d.ts
Labels: feat

#28 홈레이아웃 변경 및 기본 레이아웃 수정
  src/assets/colorlogo.png
  src/components/ClassRoom/Drawing.tsx
  src/components/common/Button.tsx
  src/components/common/ProfilePhoto.tsx
  src/components/layout/LogoArea.tsx
  src/components/layout/Nav.tsx
  src/layouts/BasicLayout.tsx
  src/layouts/RoomLayout.tsx
  src/page/Home.tsx
  src/page/Login.tsx
  src/page/SignUp.tsx
  src/router/ProtectedRoute.tsx
  src/router/Router.tsx
Labels: design

#30 홈, 마이페이지 마크업
  src/components/Login/LoginInput.tsx
  src/components/layout/LogoArea.tsx
  src/page/Home.tsx
  src/page/MyPage.tsx
  src/router/Router.tsx
  src/types/user.d.ts
Labels: design

#31 feat: jwtdecode로 유저 정보 저장
  package-lock.json
  package.json
  src/hooks/useLogin.ts
  src/main.tsx
  src/router/ProtectedRoute.tsx
Labels: feat

#32 그림판 소켓 정리
  src/components/ClassRoom/Drawing.tsx
  src/hooks/useSocket.ts
  src/hooks/useSocketEmit.ts
  src/hooks/useSocketEvent.ts
  src/types/drawing.d.ts
  src/types/socket.d.ts
Labels: feat, refactor

#33 라우터 정리 및 리드미 작성
  README.md
  index.html
  public/favicon.png
  public/vite.svg
  src/assets/colorlogo.png
  src/components/ClassRoom/Drawing.tsx
  src/components/layout/Modal.tsx
  src/components/layout/Nav.tsx
  src/page/Home.tsx
Labels: documentation, refactor

#34 refactor:채팅소켓 정리
  src/components/ClassRoom/Chat.tsx
  src/components/ClassRoom/Chatting/ChatMessage.tsx
Labels: refactor

#35 feat: 내 정보 수정 페이지 구현
  src/components/Login/LoginInput.tsx
  src/hooks/useLogin.ts
  src/main.tsx
  src/page/MyPage.tsx
Labels: feat, design
